[homelab]
homelab01 ansible_host=192.168.0.46 ansible_user=mike ansible_ssh_private_key_file=~/.ssh/homelab

[nas]
sun01 ansible_host=192.168.0.61 ansible_user=smt ansible_ssh_private_key_file=~/.ssh/localsun

[home:children]
homelab
nas
