apiVersion: v1
kind: Service
metadata:
  name: devboard-backend-canary
  namespace: devboard
  labels:
    app: devboard-backend
    rollouts.argoproj.io/service-role: canary
spec:
  selector:
    app: devboard-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
