apiVersion: apps/v1
kind: Deployment
metadata:
  name: devboard-event-frontend
  namespace: devboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devboard-event-frontend
  template:
    metadata:
      labels:
        app: devboard-event-frontend
    spec:
      containers:
        - name: event-frontend
          image: sunmingtao/devboard-event-frontend:${IMAGE_TAG}
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /events/
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /events/
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 20
