apiVersion: v1
kind: Service
metadata:
  name: devboard-event-service
  namespace: devboard
  labels:
    app: devboard-event-service
spec:
  selector:
    app: devboard-event-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  type: ClusterIP
