apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - backend-rollout.yaml
  - backend-service.yaml
  - backend-canary-service.yaml
  - backend-hpa.yaml
  - event-service-deployment.yaml
  - event-service-service.yaml
  - event-frontend-deployment.yaml
  - event-frontend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
