---
- name: Backup kafka on homelab server
  template:
    src: backup-kafka-new.sh.j2
    dest: "{{ local_bin }}/backup-kafka.sh"
    owner: root
    group: root
    mode: "0755"

- name: Install backup service
  copy:
    dest: /etc/systemd/system/backup-kafka.service
    owner: root
    group: root
    mode: "0644"
    content: |
      [Unit]
      Description=Backup kafka

      [Service]
      Type=oneshot
      ExecStart={{ local_bin }}/backup-kafka.sh

      Restart=on-failure
      RestartSec=2min
      StartLimitIntervalSec=30min
      StartLimitBurst=5

- name: Install backup timer
  copy:
    dest: /etc/systemd/system/backup-kafka.timer
    owner: root
    group: root
    mode: "0644"
    content: |
      [Unit]
      Description=Run backup-kafka.service every 24 hours

      [Timer]
      OnCalendar=*-*-* 00:40:00
      Persistent=true
      Unit=backup-kafka.service
      RandomizedDelaySec=300

      [Install]
      WantedBy=timers.target

- name: Reload systemd and enable backup timer
  systemd:
    daemon_reload: yes
    name: backup-kafka.timer
    enabled: yes
    state: started