apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - spring-actuator-servicemonitors.yaml
  - application-alert-rules.yaml
  - http-alert-rules.yaml
  - kafka-listener-alert-rules.yaml
