---
- name: Copy systemd-email-alert script to homelab server
  template:
    src: systemd-email-alert.sh.j2
    dest: /usr/local/bin/systemd-email-alert.sh
    owner: root
    group: root
    mode: "0755"

- name: Install systemd service template for email alert
  template:
    src: email-alert.service.j2
    dest: /etc/systemd/system/email-alert@.service
    owner: root
    group: root
    mode: "0644"
  

  