---
- name: Configure system hostname
  ansible.builtin.hostname:
    name: "{{ homelab_hostname }}"
  tags:
    - hostname

- name: Configure hostname entry in /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1\s+'
    line: "127.0.1.1 {{ homelab_hostname }}"
    owner: root
    group: root
    mode: "0644"
    create: true
  tags:
    - hostname
