apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: devboard
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-2
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: devboard-backend-secret
  namespace: devboard
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: devboard-backend-secret
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: devboard/dev/backend
        property: DATABASE_PASSWORD
