apiVersion: v1
kind: ConfigMap
metadata:
  name: devboard-backend-config
  namespace: devboard
data:
  SPRING_PROFILES_ACTIVE: "mysql"
  DATABASE_URL: "jdbc:mysql://devboard-dev-db.ctigw2agmnko.ap-southeast-2.rds.amazonaws.com:3306/devboard?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
  DATABASE_USERNAME: "devboard_user"
  CORS_ALLOWED_ORIGINS: "http://PLACEHOLDER_LOADBALANCER_DNS"