apiVersion: v1
kind: ConfigMap
metadata:
  name: devboard-event-service-config
  namespace: devboard
data:
  KAFKA_BOOTSTRAP_SERVERS: "devboard-kafka.devboard.svc.cluster.local:9092"
  KAFKA_CONSUMER_GROUP: "event-service"
  TASK_EVENTS_TOPIC: "devboard.tasks"
