apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devboard-ingress
  namespace: devboard
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-2:627073650332:certificate/ccc54f68-f0d5-4a68-aecb-32bfe354a903
    alb.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  rules:
    - host: www.smtdevboard.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devboard-frontend
                port:
                  number: 80