apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devboard

resources:
  - ../../base
  - backend-configmap.yaml
  - event-service-configmap.yaml
  - frontend-nginx-configmap.yaml
  - ingress.yaml

patches:
  - path: frontend-service-patch.yaml
  - target:
      kind: Deployment
      name: devboard-backend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: sunmingtao/devboard-backend:e773e36
  - target:
      kind: Deployment
      name: devboard-frontend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: sunmingtao/devboard-frontend:e773e36
  - target:
      kind: Deployment
      name: devboard-event-service
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: sunmingtao/devboard-event-service:e773e36
  - target:
      kind: Deployment
      name: devboard-event-frontend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: sunmingtao/devboard-event-frontend:e773e36
