spring:
  # MySQL Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3307/devboard?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: devboard_user
    password: devboard_pass
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # Disable H2 Console
  h2:
    console:
      enabled: false