# Development Environment Configuration  
# This profile is activated when SPRING_PROFILES_ACTIVE=dev

spring:
  # H2 Database Configuration (Development)
  datasource:
    url: jdbc:h2:mem:devboard_dev
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
    # Development connection pool (smaller)
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000

  # JPA Configuration for Development
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop  # Recreate schema on startup
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true  # Show SQL queries in development
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  # H2 Console (for development only)
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true  # Allow remote connections in dev

  # Development server configuration
  server:
    port: ${SERVER_PORT:8080}

  # Development logging
  logging:
    level:
      com.example.devboard: DEBUG
      org.springframework.web: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Development JWT Configuration
devboard:
  app:
    # Development JWT secret (256-bit)
    jwtSecret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970337336763979244226452948404D6351665468576D5A7134}
    jwtExpirationMs: ${JWT_EXPIRATION_MS:86400000}  # 24 hours for development
    
    # CORS configuration for development
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173,http://localhost:5174,http://localhost:5175}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

  # Development features
  features:
    h2-console: true
    debug-logging: true
    dev-tools: true

# Management endpoints for development
management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all endpoints in development
      base-path: /actuator
  endpoint:
    health:
      show-details: always  # Show detailed health info in development