spring:
  # H2 Database Configuration (Development)
  datasource:
    url: jdbc:h2:mem:devboard
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  
  # H2 Console (for development)
  h2:
    console:
      enabled: true
      path: /h2-console

# Development JWT Configuration
# IMPORTANT: For production, use strong secret via environment variable
devboard:
  app:
    jwtSecret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970337336763979244226452948404D6351665468576D5A7134}
    jwtExpirationMs: ${JWT_EXPIRATION_MS:86400000}