---
homelab_admin_user: mike
homelab_timezone: Australia/Sydney
homelab_manage_locale: true
homelab_locale: en_AU.UTF-8

ssh_authorized_key_file: ~/.ssh/homelab.pub
ssh_backup_path: /etc/ssh/sshd_config.ansible-pre-hardening.bak
ssh_hardening_dropin: /etc/ssh/sshd_config.d/10-homelab-hardening.conf
ssh_legacy_hardening_dropins:
  - /etc/ssh/sshd_config.d/99-homelab-hardening.conf
ssh_pubkey_authentication: true
ssh_permit_root_login: "no"
ssh_password_authentication: false
ssh_kbd_interactive_authentication: false

common_packages:
  - vim
  - curl
  - git
  - htop
  - net-tools
  - ca-certificates
  - gnupg
  - lsb-release
  - ufw
  - unzip
  - tree

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

common_apt_cache_valid_time: 3600
common_apt_upgrade: true
common_reboot_if_required: true
common_enable_unattended_security_upgrades: true

homelab_sysctl_settings:
  kernel.dmesg_restrict: 0

homelab_manage_netplan: false
homelab_network_allocation_method: router_dhcp_reservation
homelab_network_primary_interface: wlp2s0
homelab_network_reserved_ipv4: 192.168.0.46
homelab_network_prefix: 24
homelab_network_gateway: 192.168.0.1
homelab_network_mac_address: a8:a0:92:de:ad:ad
homelab_network_dns_servers:
  - 192.168.0.1

stacks_root: /opt/stacks
stacks_backup_root: /var/backups/homelab-stacks
stacks_backup_offsite_provider: s3
stacks_backup_offsite_target: ""

portainer_dir: "{{ stacks_root }}/portainer"
portainer_http_port: 9000
portainer_https_port: 9443

home_assistant_dir: "{{ stacks_root }}/home-assistant"
home_assistant_network_mode: host
home_assistant_port: 8123
