---
- name: Install msmtp msmtp-mta mailutils
  apt:
    name: 
      - msmtp 
      - msmtp-mta 
      - mailutils
    state: present
    update_cache: yes

- name: Configure msmtp
  template:
    src: msmtprc.j2
    dest: "{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
  loop:
    - /home/mike/.msmtprc
    - /root/.msmtprc
  vars:
    google_app_password: "{{ lookup('env', 'GOOGLE_APP_PASSWORD') }}"

  