apiVersion: v1
kind: Secret
metadata:
    name: devboard-backend-secret
    namespace: devboard-prod
type: Opaque
stringData:
    DATABASE_PASSWORD: ENC[AES256_GCM,data:hnoNQvFcGp63Xot15JRo6X62xqI7Jg==,iv:cpeMXiwWEtg1gdZZtihU/A6DhVP9X2P2aAX1MWdAgXc=,tag:KtXsJacu5zQA6AWLW5+cXg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:Q3t22jJ/YPcpa2E16cjDC2E0SnaWUlJZF8+Vwpzm6r+ivAQbXMp27DI=,iv:ao8c+Mdea/zXVTiPXmrAaZeg/ef+gLBnwg2tw0N4suU=,tag:XoeTJA6I7MYycu0XlL6arA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOGZvd09SL2JDaDlJcEtl
            d29WVXlxb0FHb3VZQUFYbFJ5anJTNndvSmxJCjEreGNVSTM1SGtIRWVJUmsvbnpK
            a3VTN25iUFZmL013UjdXSnY2RHh3ekUKLS0tIGpMdWF0YU1HbTNQeGliMThSTXlv
            cFc3SWN6L0Q4bWc1ckNtcjJCa01EZlEKeHsf812I7ej4ZWRDBgQRmmf/qfiJ+36i
            mpYyTg38mGOIuhdZtdTbJad0dn46QBGmOf1RKUViFwc/duFwdi4kiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xnfrlsaxxx68e09r0ayyywg6v067cstaurmwwqd3uak9etpshqasdcaew3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-23T07:12:15Z"
    mac: ENC[AES256_GCM,data:WPxxoOgtm/JkS233WpmDZ24azdiR7DC08XOHghx2IqkkK4xZlwwwUD+QLj8s/YYO5ptrSj1yYyAMKKAd8A+eEcTNW4x5/LeNe7qyfQMsGfR3vm/yuR7pseBX5ZmEoiD0CaXaX11rz3vrY08M/Sil3a+uIuEGwkgIXZkk0Bf6yeg=,iv:GkLQiQ3/KnDnJr1/83pPJpQrd9fT44aUErAtKtReXNI=,tag:X90S5dCgPbn6EaBaMUEp0w==,type:str]
    version: 3.13.1
