apiVersion: v1
kind: Secret
metadata:
  name: devboard-backend-secret
  namespace: devboard-prod
type: Opaque
stringData:
  DATABASE_PASSWORD: prodpassword-change-me
  JWT_SECRET: prod-k3s-placeholder-jwt-secret-change-me

