apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
    namespace: devboard-prod
type: Opaque
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:/+iX+2AugCDKBnhWyQn3PastgwLh9JGcuJpf,iv:u5x8klPyor1nrCHOzuvRgQtzIIw8OY2E8S1hMIsLVws=,tag:8yrbMUQ83kdzjCkvwuyfEw==,type:str]
    MYSQL_DATABASE: ENC[AES256_GCM,data:5McmkjpOErM=,iv:sItEO/Ux60tcc6gKXKFi++8XVc1Ia2c81vhHox4M5Ns=,tag:ybSdYfJz755EHQKBJTr9LA==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:1hy6IdoCFI8=,iv:NYxpt/YUk84J67Cr9LFJs0ZIuuHNs7Ptc4pETzeuft4=,tag:kDBbyQsYinB86vH94cEUZg==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:JKb/kR/22MMhCrfreX8MqXdfINCGNA==,iv:ql5gr5BXW48AMG5cKQHC6NnZ63XCZlyOUu1nwaAJ428=,tag:jpzczo1rMFZeZKESFZ3+ZQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYeGNWU0tjdTVEL05yRFdX
            d2tNRHRTNkptVW9MYmxTL1pEVVhydXduTVMwCktYU2d0amdYdWtyS0hCa2UxaFpG
            NjNNTXlzMFA1b1doR2JGT3FZMHZLYTgKLS0tIE1ZU1lGd2FBNlZFcFZTSGhPUURs
            WEV2ekJiSmRhT2NjS0RKU3NYajE2cFUK4VkpZMnnpUnk+4F64IYN+yDPNypAjARq
            /G4Oq7PihazpFZMAC9iAqR04yW65jdfRI6tdqnlMuxfpbB3CnXcCdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xnfrlsaxxx68e09r0ayyywg6v067cstaurmwwqd3uak9etpshqasdcaew3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-23T07:12:15Z"
    mac: ENC[AES256_GCM,data:RQsyFBhhtYK2RdQ9ISnuhcWLSSyATFmxXCHqXA0rX6PFbWjdFTZaCPMB3Jk7lPl/e4gfLhyTUsZByOByo2lt0DKmChj4izbUD5WFoFqmvJBZob1ZbBoOO+TLBJVtKLthP9Pr62smNFN+OdL10df6RBcjEeIXojckqpXDN44yaKU=,iv:4IVIbyvmrkHAQzYTRPMtyIAoQV2pPAL2yLZeCheaCYI=,tag:4yVoq/nlHblxeV4GABYyFQ==,type:str]
    version: 3.13.1
