apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: devboard-prod
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: prod-rootpassword-change-me
  MYSQL_DATABASE: devboard
  MYSQL_USER: produser
  MYSQL_PASSWORD: prodpassword-change-me

