apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: devboard-prod-k3s-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - backend-secret.sops.yaml
  - mysql-secret.sops.yaml
