apiVersion: v1
kind: Secret
metadata:
    name: devboard-backend-secret
    namespace: devboard-dev
type: Opaque
stringData:
    DATABASE_PASSWORD: ENC[AES256_GCM,data:OUa0hMva7dTQEU8=,iv:/VlhnBz4eBSHnwup0iaiEz0I7vKcGyWbjaxsMdsVKMc=,tag:jFCcHP3WUtE+r1t6Fq9pZg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:o/3P7c+W85pfl3Q1axnduM9zuZ+UHoxPasbW3UoMAzSNNX4ZUHz/mA==,iv:urAOxXK4IIv+A4WOM22VD1ZLobjbin5pU4GhjueMMy0=,tag:ix3jZZdJWqd5mcgXQVu8Dw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZjFsZTJTTEJJdW9ITloz
            VXNSblExOGorcG5RTkRzM1pxdjBnNDJDQWxRClA4dkhYU1lDZFBNTHNzU3dCd3dh
            NmtjQ3B4WjNIMFNwV21XbEhsMXI5U1UKLS0tIFFPRlU3ZDluWGc0RmZFeG5KeDVw
            c0VQRDZiaGJFQVJaVFNPdmxwSnMwdGMKFtpEpdBa2X4If6kR8pBg7JjZ+zwRLnSU
            JiQYWgDkFrjTOo5CEIJbgic615z46+EyQeTw8GJhdMGYSp/3JTHJ+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xnfrlsaxxx68e09r0ayyywg6v067cstaurmwwqd3uak9etpshqasdcaew3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-23T07:12:15Z"
    mac: ENC[AES256_GCM,data:AdeRrYlR41byvxZBn85zW4+Prj8Vr1taURIO3uFJBuI3cJU6nuAKyRJ9VKH83XakpSXKZalsy8JrfaZSsxcV4bOAbbt0HhSMYCFRF/bjAStgmobsYdd+UAf/qyWQDfn6Uiekc5OnJbzEcf/HfcBY79+FcppbKZ6Cwgh3pxakfww=,iv:vY8bGoTT5VlxFlWgnkSIlWUUBK7EyJyP5fOkt5Uwg2I=,tag:AU7WvqgRmo3HT/nr7Q6nQQ==,type:str]
    version: 3.13.1
