apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
    namespace: devboard-dev
type: Opaque
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:UsJuWIKOlsGBteR1,iv:j9WjSp25E5p2oT3f4qut8IhaCEav0nP6DAmdUdov+hw=,tag:VxFxs2nndLhXE+TyRfeQPA==,type:str]
    MYSQL_DATABASE: ENC[AES256_GCM,data:CdICZ7FDjD8=,iv:KCmAg5qFcqGXKG4LF3hChrQFcI+194W8pxkDhnpDV3Y=,tag:h5KGQvMf1AFO2TyNsE2kQg==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:L/3FqwBgag==,iv:scRF0uMv0bRBnUhmYQNJywSYn7qKUuOgxVRRLcCNBNI=,tag:qvFEM6ljF+BNCtE/rWBZRA==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:APSDfpJk18lqbQU=,iv:1UGh9Gt+hgfkMPjP+98QjONtohPi5pxB2vo6SdxlOnI=,tag:Ga2Qyh080oThp4GLWIqjMA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0em90VHF4em5LaGtkdHox
            dldWUS9OVUxIak5iMUdwODZDTjUySHhsWmlVCmIwdlVqQStuNjFGQmVqeVQxOXFx
            WWRmNWo1SGRQeUs1cEN4OElTV01jak0KLS0tIHZDTW1jam5jK0lHcllIVlpkdndr
            ZGpFbEtDL3ZKWnNVS3o5aEVpVUVZeW8KvzRSG2Jyac/sAufYTBdlNVhqWEB2PF4F
            xvZ4rEvBS0SO32ucV2a5UDW7RgsX0jtzH0TYFOhIuu9KW0BjFLzZYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xnfrlsaxxx68e09r0ayyywg6v067cstaurmwwqd3uak9etpshqasdcaew3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-23T07:12:15Z"
    mac: ENC[AES256_GCM,data:0t4aHwZSroTMZ2rj1LJoEIAJWndIkMUrnoiFUo+/835RDwsrNzxCcnF2c7cwxIxNbHUg0gTHURkH2dhdA6AvglhC8pulT+Fu3jpM21H8jbj3Iw8pcUhfD0K/5D3CEhsKGqPK8bxSf0Ogm2rzBT7ejOUhNEMfI2J5ba4N0NAIa+4=,iv:LCP/fVaj53Q5u1pAYJkOJHzheU3JpSeKgwazKfIRHhw=,tag:ZRsn9HQN4ICCAb06iSKSlA==,type:str]
    version: 3.13.1
