grafana:
  adminUser: admin
  adminPassword: admin
  defaultDashboardsTimezone: browser
  service:
    type: ClusterIP
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: monitoring
  serviceMonitor:
    interval: 10s
    scrapeTimeout: 10s
  additionalDataSources:
    - name: DevBoard Prometheus
      type: prometheus
      uid: devboard-prometheus
      access: proxy
      url: http://devboard-monitoring-kube-p-prometheus.monitoring:9090/
      isDefault: false

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}
    podMonitorNamespaceSelector: {}
    retention: 7d
    scrapeInterval: 10s

alertmanager:
  enabled: true
  config:
    global:
      resolve_timeout: 5m
      smtp_smarthost: smtp.gmail.com:587
      smtp_from: sunmingtao@gmail.com
      smtp_auth_username: sunmingtao@gmail.com
      smtp_auth_password_file: /etc/alertmanager/secrets/alertmanager-gmail-smtp/app-password
      smtp_require_tls: true
    route:
      receiver: demo-null
      group_by:
        - namespace
        - alertname
        - job
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      routes:
        - receiver: devboard-email
          matchers:
            - alertname =~ "DevBoard.*"
        - receiver: demo-null
          matchers:
            - alertname = "Watchdog"
          repeat_interval: 12h
    receivers:
      - name: demo-null
      - name: devboard-email
        email_configs:
          - to: sunmingtao@gmail.com
            send_resolved: true
            headers:
              subject: '[DevBoard] {{ .Status }} {{ .CommonLabels.alertname }}'
  alertmanagerSpec:
    retention: 120h
    secrets:
      - alertmanager-gmail-smtp
