---
- name: Backup mysql on homelab server
  template:
    src: backup-mysql.sh.j2
    dest: "{{ local_bin }}/backup-mysql.sh"
    owner: root
    group: root
    mode: "0755"

- name: Install backup service
  copy:
    dest: /etc/systemd/system/backup-mysql.service
    owner: root
    group: root
    mode: "0644"
    content: |
      [Unit]
      Description=Backup mysql

      [Service]
      Type=oneshot
      ExecStart={{ local_bin }}/backup-mysql.sh

      Restart=on-failure
      RestartSec=2min
      StartLimitIntervalSec=30min
      StartLimitBurst=5

- name: Install backup timer
  copy:
    dest: /etc/systemd/system/backup-mysql.timer
    owner: root
    group: root
    mode: "0644"
    content: |
      [Unit]
      Description=Run backup-mysql.service every 24 hours

      [Timer]
      OnCalendar=*-*-* 00:20:00
      Persistent=true
      Unit=backup-mysql.service
      RandomizedDelaySec=300

      [Install]
      WantedBy=timers.target

- name: Reload systemd and enable backup timer
  systemd:
    daemon_reload: yes
    name: backup-mysql.timer
    enabled: yes
    state: started