apiVersion: v1
kind: ConfigMap
metadata:
  name: ksops-cmp-plugin
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: ksops
    spec:
      version: v1.0
      discover:
        fileName: secrets-generator.yaml
      generate:
        command:
          - kustomize
        args:
          - build
          - --enable-alpha-plugins
          - --enable-exec
          - .
