apiVersion: v1
kind: ConfigMap
metadata:
  name: ksops-cmp-plugin
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: ksops
    spec:
      version: ksops-v1.0
      discover:
        find:
          command:
            - sh
            - -c
            - find . \( -name 'secrets-generator.yaml' -o -name '*-secret.sops.yaml' \) | grep -q .
      generate:
        command:
          - sh
          - -c
          - kustomize build --enable-alpha-plugins --enable-exec .
