apiVersion: generators.external-secrets.io/v1alpha1
kind: Fake
metadata:
  name: devboard-backend-secret-source
  namespace: devboard
spec:
  data:
    DATABASE_PASSWORD: devpassword
    JWT_SECRET: replace-with-base64-secret-from-openssl-rand-base64-64
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: devboard-backend-secret
  namespace: devboard
spec:
  refreshInterval: 1h
  target:
    name: devboard-backend-secret
    creationPolicy: Owner
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Fake
          name: devboard-backend-secret-source
