apiVersion: generators.external-secrets.io/v1alpha1
kind: Fake
metadata:
  name: devboard-backend-secret-source
  namespace: devboard
spec:
  data:
    DATABASE_PASSWORD: devpassword
    JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970337336763979244226452948404D6351665468576D5A7134
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: devboard-backend-secret
  namespace: devboard
spec:
  refreshInterval: 1h
  target:
    name: devboard-backend-secret
    creationPolicy: Owner
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Fake
          name: devboard-backend-secret-source
