apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devboard

resources:
  - ../../base
  - mysql-deployment.yaml
  - mysql-service.yaml
  - mysql-pvc.yaml
  - mysql-secret.yaml
  - backend-configmap.yaml
  - backend-secret.yaml
  - event-service-configmap.yaml
  - frontend-nginx-configmap.yaml
  - ingress.yaml
