apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: devboard
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_DATABASE: devboard
  MYSQL_USER: devuser
  MYSQL_PASSWORD: devpassword