---
- import_playbook: bootstrap.yml
- import_playbook: ssh.yml
- import_playbook: docker.yml
- import_playbook: sysctl.yml
- import_playbook: netplan.yml
- import_playbook: stacks.yml
- import_playbook: k3s.yml
- import_playbook: argocd.yml
- import_playbook: devboard.yml
