name: Deploy Frontend to Dev Environment

on:
  push:
    branches:
      - develop
    paths:
      - 'devboard-frontend/**'
      - '.github/workflows/deploy-dev-frontend.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      working-directory: ./devboard-frontend
      run: npm ci
    
    - name: Run tests
      working-directory: ./devboard-frontend
      run: npm run test:run || echo "Tests failed but continuing deployment"
      continue-on-error: true
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Get ALB DNS name
      id: get-alb-dns
      run: |
        ALB_DNS=$(aws elbv2 describe-load-balancers \
          --names devboard-dev-alb \
          --query 'LoadBalancers[0].DNSName' \
          --output text)
        echo "ALB_DNS=$ALB_DNS" >> $GITHUB_OUTPUT
    
    - name: Get CloudFront domain for dev environment  
      id: get-dev-cf-domain
      run: |
        CF_DOMAIN=$(aws cloudfront list-distributions \
          --query "DistributionList.Items[?contains(Origins.Items[0].DomainName, 'devboard-dev-frontend')].DomainName | [0]" \
          --output text)
        
        if [ "$CF_DOMAIN" == "None" ] || [ -z "$CF_DOMAIN" ]; then
          echo "Development CloudFront not deployed yet. Please run 'terraform apply' first."
          exit 1
        fi
        
        echo "DEV_CF_DOMAIN=$CF_DOMAIN" >> $GITHUB_OUTPUT
        echo "Development CloudFront domain: $CF_DOMAIN"

    - name: Build frontend for development
      working-directory: ./devboard-frontend
      env:
        # Replace placeholder with actual CloudFront domain
        VITE_API_URL: https://${{ steps.get-dev-cf-domain.outputs.DEV_CF_DOMAIN }}
        VITE_API_BASE_URL: https://${{ steps.get-dev-cf-domain.outputs.DEV_CF_DOMAIN }}/api
      run: npm run build:dev
    
    - name: Get S3 bucket and CloudFront ID
      id: get-resources
      run: |
        S3_BUCKET="devboard-dev-frontend-${{ secrets.AWS_ACCOUNT_ID }}"
        echo "S3_BUCKET=$S3_BUCKET" >> $GITHUB_OUTPUT
        echo "Using S3 bucket: $S3_BUCKET"
        
        # Get CloudFront distribution ID by looking for S3 origin domain
        echo "Looking for CloudFront distribution..."
        CF_DIST_ID=$(aws cloudfront list-distributions \
          --query "DistributionList.Items[?contains(Origins.Items[0].DomainName, '${S3_BUCKET}')].Id | [0]" \
          --output text)
        
        if [ "$CF_DIST_ID" == "None" ] || [ -z "$CF_DIST_ID" ]; then
          echo "CloudFront distribution not found for bucket ${S3_BUCKET}"
          echo "Available distributions:"
          aws cloudfront list-distributions --query "DistributionList.Items[*].[Id,Origins.Items[0].DomainName]" --output table
          exit 1
        fi
        
        echo "CF_DIST_ID=$CF_DIST_ID" >> $GITHUB_OUTPUT
    
    - name: Deploy to S3
      working-directory: ./devboard-frontend
      run: |
        aws s3 sync dist/ s3://${{ steps.get-resources.outputs.S3_BUCKET }} --delete
    
    - name: Invalidate CloudFront
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ steps.get-resources.outputs.CF_DIST_ID }} \
          --paths "/*"
    
    - name: Get CloudFront domain
      id: get-cf-domain
      run: |
        CF_DOMAIN=$(aws cloudfront get-distribution \
          --id ${{ steps.get-resources.outputs.CF_DIST_ID }} \
          --query 'Distribution.DomainName' \
          --output text)
        echo "CF_DOMAIN=$CF_DOMAIN" >> $GITHUB_OUTPUT
    
    - name: Display dev environment URLs
      run: |
        echo "=== Development Environment URLs ==="
        echo "Frontend URL: https://${{ steps.get-dev-cf-domain.outputs.DEV_CF_DOMAIN }}"
        echo "Backend API (via CloudFront): https://${{ steps.get-dev-cf-domain.outputs.DEV_CF_DOMAIN }}/api"
        echo "Backend API (direct ALB): http://${{ steps.get-alb-dns.outputs.ALB_DNS }}/api"