services:
  gmail-auto-reply:
    image: ghcr.io/sunmingtao/gmail-auto-reply:latest
    container_name: gmail-auto-reply
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/application_default_credentials.json
      GMAIL_TOKEN_FILE: /secrets/token.json
      GMAIL_CLIENT_SECRET_FILE: /secrets/gmail-api-client-secret.json
      OLLAMA_HOST: http://host.docker.internal:11434
    volumes:
      - /opt/gmail-auto-reply/secrets:/secrets

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json:ro
    command: >
      --interval 300
      --cleanup
      gmail-auto-reply